version: '3'
services:
  web:
    image: "covid-flask"
    restart: always
    ports:
      - "5002:5000"
    volumes:
      - .:/covid
    command: "flask run --host=0.0.0.0 --port=5000"
  redis:
    image: "redis:alpine"
